<a href="https://colab.research.google.com/github/ilbaks/LLM_start/blob/main/02_Pytorch_Basics/02_pytorch_basics_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.Pytorch Basics

# 0.Imports and Installs

In [37]:
import torch
import numpy as np

## 1. Tensor basics

Everything in pytorch is based on Tensor operations.
A tensor can have different dimensions
so it can be 1d, 2d, or even 3d and higher

scalar, vector, matrix, tensor

### torch.empty(size): uninitiallized



In [6]:
x = torch.empty(0)
print(x)

tensor([])


In [4]:
x = torch.empty(1)  # scalar
print(x)

tensor([-2.4082e-38])


In [5]:
x = torch.empty(3)  # vector
print(x)

tensor([3.7847e-04, 3.1896e-41, 4.0509e-04])


In [8]:
x = torch.empty(2, 4) # matrix, 2D
print(x)

tensor([[-4.0334e-30,  7.0065e-45,  1.0790e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [9]:
x = torch.empty(2,4,6) # tensor, 3D
print(x)

tensor([[[2.1715e-18, 2.6704e-06, 1.3679e+22, 2.0450e+20, 1.3484e-05,
          8.2356e-10],
         [6.7204e-07, 4.2886e-08, 4.2056e-05, 2.6102e-09, 1.4580e-19,
          1.1495e+24],
         [3.0881e+29, 1.5766e-19, 1.8889e+31, 7.2065e+31, 2.8404e+29,
          2.3089e-12],
         [1.9421e+31, 2.7491e+20, 6.1949e-04, 1.9421e+31, 2.7491e+20,
          2.3078e-12]],

        [[7.1760e+22, 7.2250e+28, 1.5766e-19, 4.2192e-08, 2.1666e-04,
          3.2768e-09],
         [8.5493e+20, 1.0386e+21, 2.1458e-07, 4.2252e-05, 8.3385e-10,
          2.3053e-12],
         [2.6302e+20, 6.1949e-04, 6.4805e-10, 2.5204e-09, 2.5928e-09,
          6.9118e-04],
         [6.7743e-10, 6.7122e-07, 2.7149e-06, 1.4580e-19, 4.5450e+30,
          1.8524e+28]]])


### torch.rand(size) random numbers from [0, 1]

In [11]:
x = torch.rand(3, 5)
print(x)

tensor([[0.5742, 0.8729, 0.6403, 0.2695, 0.4463],
        [0.8012, 0.3559, 0.3369, 0.0440, 0.6584],
        [0.7371, 0.8095, 0.0812, 0.3585, 0.1946]])


- torch.zeros(size)
- torch.ones(size)

In [12]:
x = torch.zeros(3, 4, 5)
print(x)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])


In [13]:
x = torch.ones (1, 4)
print(x)

tensor([[1., 1., 1., 1.]])


- check size x.size()

In [16]:
x = torch.zeros(4, 3, 5)
x.size()

torch.Size([4, 3, 5])

- check type

In [17]:
x.dtype

torch.float32

### construct from data

In [18]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


### requires grad argument

In [20]:
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


### operations

In [25]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

print(x, y)
print("x + y=", x + y)
print(torch.add(x, y))
print(y.add_(x))
print(x - y)
print(x * y)
print(torch.mul(x, y))
print(x / y)
print( torch.div(x, y))



tensor([[0.8901, 0.2420],
        [0.0595, 0.3032]]) tensor([[0.0094, 0.1762],
        [0.5787, 0.7729]])
x + y= tensor([[0.8995, 0.4181],
        [0.6383, 1.0761]])
tensor([[0.8995, 0.4181],
        [0.6383, 1.0761]])
tensor([[0.8995, 0.4181],
        [0.6383, 1.0761]])
tensor([[-0.0094, -0.1762],
        [-0.5787, -0.7729]])
tensor([[0.8007, 0.1012],
        [0.0380, 0.3263]])
tensor([[0.8007, 0.1012],
        [0.0380, 0.3263]])
tensor([[0.9896, 0.5787],
        [0.0933, 0.2817]])
tensor([[0.9896, 0.5787],
        [0.0933, 0.2817]])


### slicing

In [28]:
x = torch.rand(5, 3)
print(x)
print(x[:, 0])  # all rows and 1 column
print(x[0, : ])  # row 1 and all columns
print(x[0, 0])# element at 1, 1
print(x[0, 0].item())  # Get the actual value if only 1 element in your tensor

tensor([[0.6004, 0.5449, 0.6169],
        [0.3612, 0.0161, 0.1193],
        [0.1364, 0.2887, 0.3590],
        [0.4113, 0.4350, 0.5988],
        [0.6148, 0.8987, 0.5094]])
tensor([0.6004, 0.3612, 0.1364, 0.4113, 0.6148])
tensor([0.6004, 0.5449, 0.6169])
tensor(0.6004)
0.6003619432449341


### reshape

In [29]:
x = torch.rand(4, 4)
print(x)

In [32]:
y = x.view(16)  # make in 1 dimension with 16
z = x.view(-1, 8)  # make second dimension 8
print(y, y.size())
print(z, z.size())


tensor([0.7433, 0.6902, 0.4909, 0.0018, 0.1425, 0.3744, 0.0073, 0.1982, 0.0796,
        0.0455, 0.9417, 0.3317, 0.1222, 0.6917, 0.3028, 0.4550]) torch.Size([16])
tensor([[0.7433, 0.6902, 0.4909, 0.0018, 0.1425, 0.3744, 0.0073, 0.1982],
        [0.0796, 0.0455, 0.9417, 0.3317, 0.1222, 0.6917, 0.3028, 0.4550]]) torch.Size([2, 8])


In [35]:
z.dtype, type(z)

(torch.float32, torch.Tensor)

### Numpy

In [36]:
# torch to numpy with .numpy()
x = torch.ones(5)
print(x)

y = x.numpy()
print(type(y), y)

# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
x.add_(1)
print(x)
print(y)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'> [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [39]:
# numpy to torch with .from_numpy(x)
x = np.ones(5)
y = torch.from_numpy(x)
print(y)

# again be careful when modifying
x += 1
print(x)
print(y)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### tensors on CPU or on GPU

In [41]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")
    z = z.numpy()